### PR TITLE
Added used languages tags. Closes #4

### LINKED ISSUE #4: Added used languages tags
API samples: https://api.github.com/repos/{owner}/{repo}/languages

### PR DESCRIPTION
**Pull request by tarsisazevedo**
add languages and some css. preview:
screen shot 2015-04-11 at 11 00 16 pm

### CODE REVIEW

**Comment by jbochi** [comment]
Awesome, but would you mind rebasing your commits? It's not merging cleanly. :(

**Comment by jbochi** [comment]
I merged it manually. Thanks!!

**Comment by tarsisazevedo** [comment]
sorry @jbochi! I just saw it :)

**Comment by jbochi** [comment]
No problem. We almost won the #hackinpoa thanks to you. :P

**Pull request closed without merging**
